### ISSUE TITLE
Cash whole segment of video

### ISSUE THREAD

**Issue by ionyshch-prismsl** [prismai/cvat#2]
Segment i.e. all frames that correspond to single job must be cached on a client (in JavaScript).
Comment will describe, how this was actually done.

- Now this._MAX_LOAD in FrameProvider is set to 1050, which means, that operators, when creating task must choose segment size and overlap, so that their sum was less than or equal to 1050.
- Related issues is that, when and how FrameProvider actually downloads frames. Ask operators, how they do it now. When I experimented with it, I just pressed "play" button and waited until it finished. It took me 10 minutes to cache the whole segment (job).

**Comment by Ellirid-PrismAI** [comment]
FrameProvider downloads frames from 1 to value of _MAX_LOAD var right when the user open the annotation page (`/?id=`)
